### ISSUE TITLE
[V3] - Version 3 release

### ISSUE THREAD

**Issue by DaneSirois** [DaneSirois/npm-redux-interfaces#27]
- [x] [Added a `.listen()` method to reducers](https://github.com/DaneSirois/npm-redux-interfaces/issues/4)
- [x] [Changed `.mountInterface()` to just .mount()](https://github.com/DaneSirois/npm-redux-interfaces/issues/26)
- [x] Removed `.connectInterface()` method
- [x] [Made reducer paths not be function calls](https://github.com/DaneSirois/npm-redux-interfaces/issues/25)
- [ ] Added section to README outlining release
